name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Lint Check
        run: flake8 main.py
      - name: Static Analysis
        if: ${{ success() }}
        run: mypy --strict main.py
      - name: Unit Tests
        if: ${{ success() }}
        run: pytest -v ./src
      - name: Execute Program
        if: ${{ success() }}
        run: python main.py
